const state={manifest:null,events:[]};
const $=id=>document.getElementById(id);
const collator=new Intl.Collator('cs');
const dateFmt=new Intl.DateTimeFormat('cs-CZ',{weekday:'short',day:'numeric',month:'numeric',year:'numeric'});
const shortDateFmt=new Intl.DateTimeFormat('cs-CZ',{day:'numeric',month:'numeric',year:'numeric'});
const timeFmt=new Intl.DateTimeFormat('cs-CZ',{hour:'2-digit',minute:'2-digit'});
function eventStart(e){return new Date(e.start_at)}
function eventEnd(e){return new Date(e.end_at||e.start_at)}
function isFuture(e){return eventEnd(e)>=new Date()}
function sameDay(a,b){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function text(e){return [e.title,e.description,e.venue,e.municipality,...(e.categories||[])].filter(Boolean).join(' ').toLocaleLowerCase('cs')}
function priceKind(e){return e.price?.type||'unknown'}
function fmtWhen(e){const s=eventStart(e);const end=e.end_at?eventEnd(e):null;if(e.all_day){if(end&&!sameDay(s,end))return `${dateFmt.format(s)}\n– ${dateFmt.format(end)}`;return `${dateFmt.format(s)}\ncelý den`}if(end&&!sameDay(s,end))return `${dateFmt.format(s)} ${timeFmt.format(s)}\n– ${shortDateFmt.format(end)} ${timeFmt.format(end)}`;if(end)return `${dateFmt.format(s)}\n${timeFmt.format(s)}–${timeFmt.format(end)}`;return `${dateFmt.format(s)}\n${timeFmt.format(s)}`}
function sourceLabel(type){return ({official:'Oficiální zdroj',facebook:'Facebook',ticketing:'Prodej vstupenek',regional:'Regionální kalendář'})[type]||'Zdroj'}
function fillSelect(id,values){const el=$(id);values.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;el.appendChild(o)})}
function unique(values){return [...new Set(values.filter(Boolean))].sort(collator.compare)}
async function load(){try{const m=await fetch('data/manifest.json',{cache:'no-store'});if(!m.ok)throw new Error(`Manifest: HTTP ${m.status}`);state.manifest=await m.json();const files=state.manifest.weeks.map(w=>fetch(w.file,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`${w.file}: HTTP ${r.status}`);return r.json()}));const weeks=await Promise.all(files);state.events=weeks.flatMap(w=>w.events||[]);fillSelect('week',state.manifest.weeks.map(w=>w.id));fillSelect('municipality',unique(state.events.map(e=>e.municipality)));fillSelect('category',unique(state.events.flatMap(e=>e.categories||[])));document.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',render));$('updated').textContent=`Aktualizováno ${new Intl.DateTimeFormat('cs-CZ',{dateStyle:'medium',timeStyle:'short'}).format(new Date(state.manifest.generated_at))}`;render()}catch(err){$('error').hidden=false;$('error').textContent=`Data se nepodařilo načíst: ${err.message}`;$('count').textContent='Chyba načítání';console.error(err)}}
function render(){const q=$('search').value.trim().toLocaleLowerCase('cs');const week=$('week').value;const municipality=$('municipality').value;const category=$('category').value;const price=$('price').value;const future=$('futureOnly').checked;const filtered=state.events.filter(e=>!q||text(e).includes(q)).filter(e=>!week||e.week===week).filter(e=>!municipality||e.municipality===municipality).filter(e=>!category||(e.categories||[]).includes(category)).filter(e=>!price||priceKind(e)===price).filter(e=>!future||isFuture(e)).sort((a,b)=>eventStart(a)-eventStart(b)||collator.compare(a.title,b.title));$('count').textContent=`${filtered.length} akcí`;const root=$('events');root.innerHTML='';if(!filtered.length){const d=document.createElement('div');d.className='empty';d.textContent='Žádné akce neodpovídají zvoleným filtrům.';root.appendChild(d);return}const tpl=$('event-template');filtered.forEach(e=>{const n=tpl.content.cloneNode(true);n.querySelector('.event-date').textContent=fmtWhen(e);n.querySelector('.event-category').textContent=(e.categories||[]).join(' · ');n.querySelector('.event-price').textContent=e.price?.text||'Vstupné neuvedeno';n.querySelector('.event-title').textContent=e.cancelled?`${e.title} — ZRUŠENO`:e.title;n.querySelector('.event-place').textContent=[e.venue,e.municipality].filter(Boolean).join(', ');n.querySelector('.event-description').textContent=e.description||'';n.querySelector('.event-verification').textContent=sourceLabel(e.source?.type);const a=n.querySelector('.event-source');a.href=e.source.url;a.textContent='Otevřít konkrétní zdroj';root.appendChild(n)})}
load();
